language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
  - npm install hexo-cli -g

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save


script:
  - hexo clean
  - hexo generate

after_script:
  - git clone ${GH_REF} pub_wb
  - cp -rf public/* pub_wb/
  - cd pub_wb
  - git config user.name "penguinalston"
  - git config user.email "forevershao1119@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder :$(date '+%Y-%m-%d %H:%M:%S' -d '+8 hour')"
  - git push origin master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: https://PenguinAlston:${git for Travis CI}@github.com/PenguinAlston/penguinalston.github.io.git #设置GH_REF，注意更改yourname,GITHUB_TOKEN:就是我们在travis-ci仓库中配置的环境变量
   #https://github.com/PenguinAlston/penguinalston.github.io.git